version = 0.1

[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "drex7"
github_repo = "incident-reporting-app"
deployment_branch = "main"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::605134436600:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-MGE02xOLKOk3"
cloudformation_execution_role = "arn:aws:iam::605134436600:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-23FXejtrstlV"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-dodfx1fjktwh"
image_repository = "605134436600.dkr.ecr.eu-west-1.amazonaws.com/aws-sam-cli-managed-dev-pipeline-resources-imagerepository-to8s25699srz"
region = "eu-west-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::605134436600:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-jfQ0S3d3wlSx"
cloudformation_execution_role = "arn:aws:iam::605134436600:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-fE8AUrmTOqPX"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-xydjn7ndeova"
image_repository = "605134436600.dkr.ecr.eu-central-1.amazonaws.com/aws-sam-cli-managed-prod-pipeline-resources-imagerepository-cmio6gkcuvxb"
region = "eu-central-1"
