AWSTemplateFormatVersion: "2010-09-09"
Description: Top-level stack template that deploys a City .

Parameters:
  AppName: { Type: String, Default: Taskify }
  ProjectTag: { Type: String, Default: "incident-app" }
  # TemplatesURL: 
  #   Type: String
  

Resources:
  AmplifyStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub './amplify-stack.yaml'

Outputs:
  AmplifyAppId:
    Value: !GetAtt AmplifyStack.Outputs.AmplifyAppId
  AmplifyAppName:
    Value: !GetAtt AmplifyStack.Outputs.AmplifyAppName