AWSTemplateFormatVersion: "2010-09-09"
Description: Top-level stack template that deploys a City .

Parameters:
  AppName: { Type: String, Default: Taskify }
  ProjectTag: { Type: String, Default: "incident-app" }
  GitRepoUrl: { Type: String, Default: https://github.com/drex7/cmrp-frontend.git }
  GitHubTokenSecret: { Type: String, Default: cmrp-frontend/token }

Resources:

  # ---- Amplify resources --------
  AmplifyRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AmplifyServiceRole
      Description: IAM role assumed by AWS Amplify to build and deploy apps
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: amplify.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess-Amplify

  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: IncidentReportingAmplifyApp
      Description: Incident Reporting App
      Repository: !Ref GitRepoUrl
      IAMServiceRole: !GetAtt AmplifyRole.Arn
      AccessToken: !Sub '{{resolve:secretsmanager:${GitHubTokenSecret}:SecretString:GithubAccessToken_}}'
      BuildSpec: |
        version: 1
        backend:
          phases:
            build:
              commands:
                - yarn install --frozen-lockfile --cache-folder .yarn-cache --prefer-offline
                - echo $AWS_BRANCH
                - |
                  case "${AWS_BRANCH}" in
                    main)
                        echo "Deploying main branch"
                        npx ampx pipeline-deploy --branch $AWS_BRANCH --app-incidentId $AWS_APP_ID
                        ;;
                    dev)
                        echo "Deploying dev branch"
                        npx ampx pipeline-deploy --branch $AWS_BRANCH --app-incidentId $AWS_APP_ID
                        ;;
                    feature*)
                        echo "Deploying feature branch"
                        npx ampx generate outputs --branch previews --app-incidentId $AWS_APP_ID
                        ;;
                    *)
                        echo "No deployment for branch ${AWS_BRANCH}"
                        ;;
                  esac
        frontend:
          phases:
            preBuild:
              commands:
                - npx ng version
            build:
              commands:
                - npx ng build --configuration=production
          artifacts:
            baseDirectory: dist/cmrp-frontend/browser
            files:
              - '**/*'
          cache:
            paths:
              - .npm/**/*
              - node_modules/**/*

  MainBranch:
    Type: AWS::Amplify::Branch
    DependsOn: AmplifyApp
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: main
      EnableAutoBuild: true
      Stage: PRODUCTION

  DevBranch:
    Type: AWS::Amplify::Branch
    DependsOn: AmplifyApp
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: dev
      EnableAutoBuild: true
      Stage: DEVELOPMENT


  # DynamoDB Table for storing incident reports
  IncidentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
        SSEType: AES256

      AttributeDefinitions:
        - AttributeName: incidentId
          AttributeType: S
        - AttributeName: category
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: reportedAt
          AttributeType: S
        - AttributeName: reportedBy
          AttributeType: S
        - AttributeName: region
          AttributeType: S
        - AttributeName: district
          AttributeType: S
        - AttributeName: assignedTo
          AttributeType: S
      KeySchema:
        - AttributeName: incidentId
          KeyType: HASH

      GlobalSecondaryIndexes:
        - IndexName: ByStatusIndex
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: reportedAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: ByCategoryIndex
          KeySchema:
            - AttributeName: category
              KeyType: HASH
            - AttributeName: incidentId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: ByReportedByIndex
          KeySchema:
            - AttributeName: reportedBy
              KeyType: HASH
            - AttributeName: incidentId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: ByAssignedToIndex
          KeySchema:
            - AttributeName: assignedTo
              KeyType: HASH
            - AttributeName: incidentId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: ByRegionIndex
          KeySchema:
            - AttributeName: region
              KeyType: HASH
            - AttributeName: incidentId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL    
        - IndexName: ByDistrictCategoryIndex
          KeySchema:
            - AttributeName: district
              KeyType: HASH
            - AttributeName: category
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Name
          Value: !Sub "${AppName}-IncidentReportsTable"
        - Key: ProjectTag
          Value: !Ref ProjectTag

Outputs:
  AmplifyAppId:
    Description: The incidentId of the deployed Amplify application
    Value: !GetAtt AmplifyApp.AppId
  AmplifyAppName:
    Description: The name of the deployed Amplify application
    Value: !GetAtt AmplifyApp.AppName
  IncidentTableName:
    Description: The name of the DynamoDB table for incident reports
    Value: !Ref IncidentTable
